HTTP/2 200 
date: Sun, 04 Oct 2026 11:07:20 GMT
content-type: binary/octet-stream
content-length: 4601856
last-modified: Thu, 15 Nov 2018 00:41:19 GMT
etag: "5ef396982b248177d14a46f03f60cc8f"
x-amz-storage-class: INTELLIGENT_TIERING
x-amz-version-id: F9sKx._PBLK89rd0gOmg7kSlkmzEQ7Oh
accept-ranges: bytes
server: cloudflare
x-cache: Miss from cloudfront
via: 1.1 55a99b6e5123bd19621debc3555080a0.cloudfront.net (CloudFront)
x-amz-cf-pop: VIE50-P4
x-amz-cf-id: 29Jbrg3e0y9AnA_Xxjr0oqZwNAMXfk3blIkLV6YvTyJoWFcFaE_A9A==
cf-cache-status: DYNAMIC
cf-ray: a453b8e96b2ad51d-PRG

